### ISSUE TITLE
Sometimes opens new container in beta when configured not to

### ISSUE THREAD

**Issue by grenzor** [stoically/temporary-containers#277]
In the beta TC in automatic mode always opens a new container when using left click (maybe others as well) even though my global isolation settings don't isolate for the same site. I haven't changed any of my settings since the upgrade to beta. Even creating a per domain setting for the site to never option a TC it will still create a TC.

**Comment by stoically** [comment]
I'm unfortunately unable to reproduce that. Could you maybe provide a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log)? That'd be really helpful!

It might be related to your comment https://github.com/stoically/temporary-containers/issues/276#issue-461851442

> by the way TC doesn't save Global Isolation settings when you configure in the popup, I can open new issue if you want

This hints to the fact that something is wrong. Could you open the Browser Toolbox (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>I</kbd>), clear the console (trash icon top left) and then configure something in the Global Isolation and see if something pops up in the console? (with debugging enabled)

**Comment by stoically** [comment]
> and provide me the console output

You might want to remove the "savePreferences" entry if it popups up though, because it'd include all your preferences including the list of per domain isolations.

**Comment by stoically** [comment]
However, an export of your preferences would also be very helpful. Might want to remove the per domain isolation list from the JSON.

**Comment by grenzor** [comment]
Prefs: https://send.firefox.com/download/bdb4201a0e70c1be/#HjHuIe78dGZpLEepvHUjIg

Will do the debug soon

**Comment by stoically** [comment]
Thanks! You have the MAC Isolation enabled, which might be the cause for left clicks isolating?

**Comment by grenzor** [comment]
That seems to be the one. The description for it says it should only open a TC if a permanent container tries to load an unassigned domain. Did the behavior of the option change in beta?

**Comment by stoically** [comment]
Just to make sure, in your case you assigned the domain you're clicking with [MAC](https://github.com/mozilla/multi-account-containers) to always open in the permanent container you're currently in?

**Comment by grenzor** [comment]
The domain is not assigned with MAC. I also didn't open any permanent container, any navigation or clicking was only from a temporary one.

**Comment by stoically** [comment]
> Did the behavior of the option change in beta?

The behavior should've not changed, but there's some substantial Isolation/Request-Handling refactoring in the beta (which allowed me to implement #225), so that might've introduced a bug (I'm relying on the tests to cover everything, and they're green).

**Comment by stoically** [comment]
> The domain is not assigned with MAC

In this case the mentioned refactoring actually made it better and now behaves as expected. With MAC Isolation enabled, the target domain needs to be assigned with MAC, otherwise it should isolate (I've added a more explanatory note to the MAC preferences).

**Comment by grenzor** [comment]
But doesn't that mean if that setting is enabled any navigation/click to any domain not assigned to MAC will open in new TC for every single page rather than for each domain according to Isolation settings? That seems like a bug, no? Maybe I'm just confused and don't understand properly

**Comment by stoically** [comment]
Oh, wait, you're right,

> I also didn't open any permanent container, any navigation or clicking was only from a temporary one.

Of course MAC Isolation should only apply if you're currently in a permanent container. Just tested, and that is indeed a bug. Looking into it, thanks!

**Comment by stoically** [comment]
Ok, fixed that one. Good catch!

That leaves us with

> by the way TC doesn't save Global Isolation settings when you configure in the popup

Would be great if you could provide a debug log for that as described in https://github.com/stoically/temporary-containers/issues/277#issuecomment-506658844. Thanks!

**Comment by grenzor** [comment]
I think Global Isolation settings in the popup is actually working (just tested again). I probably left the settings page open and forgot to refresh it to show the changes

**Comment by stoically** [comment]
[v1.0beta6](https://github.com/stoically/temporary-containers/releases/tag/v1.0beta6) includes the bugfix. I've also added an automatic refresh of the preferences page in case preferences are changed in another tab or in the popup.

**Comment by grenzor** [comment]
@stoically
I came across a similar issue in 1.0beta15 where clicking on links and even going back in tab history within a TC sometimes opens the domain/page in a new TC when it shouldn't. It doesn't happen always but it does happen somewhat frequently. Could it be related to this issue?

**Comment by stoically** [comment]
Not sure what's the reason, since it doesn't happen for me. :/ Would you mind providing another export of the preferences you encounter the problem with, so I can't test with that? Also, steps to reproduce or a debug log would be great. Thanks for letting me know!

**Comment by grenzor** [comment]
prefs: https://send.firefox.com/download/922241862da90166/#GPMphxdVhhil2Clz2CIiIw

I faced the issue on Github where it happened every time I clicked 'Issues'. I restarted Firefox and tried again and it doesn't happen. I hadn't restarted Firefox since updating to latest beta, maybe something to do with this? I'll see if I can reproduce again.

**Comment by grenzor** [comment]
@stoically
Ok, was able to reproduce. `https://github.com/stoically` was the link in the debug and refreshing the page or clicking 'Overview' on that page makes it keep opening in a new TC. Once it happens it will keep happening for that particular link when it is refreshed/clicked to. 

Log: https://send.firefox.com/download/b9295cc8c9f06012/#ZWGQvlW50GQk2KZBJpIT7g

**Comment by stoically** [comment]
Thanks for providing the prefs and log! It seems like the refactorings in #184 introduced a bug where mouseclicks stay isolated - so I guess that's another reason to look into implementing https://github.com/stoically/temporary-containers/issues/184#issuecomment-507392736 instead of trying to apply workaround-patches.

**Comment by stoically** [comment]
Should be fixed in [v1.0beta16](https://github.com/stoically/temporary-containers/releases), please let me know if not.

**Comment by stoically** [comment]
Also, btw, in case you test 1.0beta16 and wonder why the Isolation Glossary is expanded, that's a bug with the Expand Preference, as its collapsed by default, and it shouldnt expand the glossary even when that's activated.

**Comment by grenzor** [comment]
>in case you test 1.0beta16 and wonder why the Isolation Glossary is expanded

You read my mind :)

Also so far so good haven't seen any new TCs opening incorrectly yet while browsing. I'll keep a look on it

**Comment by grenzor** [comment]
@stoically
Unfortunately it still happens, though the particular link doesn't keep opening a new TC after it happens like before. Left clicked on TC github page link from tmp1441 but it opened in a new TC in tmp1445.

Log: https://send.firefox.com/download/366657e89f97c171/#w5sPHxaQqsfgsb2ceMScRQ

**Comment by stoically** [comment]
Now you're too fast for the timed cleanup, hah. Can get reproduced if you middle-click a link and then left-click the same link in under 1.5s. I should add something to the refactoring in #184 that additionally checks left vs middle/ctrlleft, and only isolates in the same / opened tab respectively.

**Comment by stoically** [comment]
Closing this in favor of #184, since the last reported issue is about mouse click timing, which is handled there.
