### ISSUE TITLE
What recent change has started causing this?

### ISSUE THREAD

**Issue by Zlewness** [stoically/temporary-containers#71]
I think in the past version or two the behavior of this extension has changed. As an explanation, I've changed the shell "\Classes\FirefoxURL-\shell\open\command" to ""firefox.exe" -osint -private-window "%1"" so when I click on a link on an external program it opens in a private window in Firefox.

Recently as well as opening the link in a private window this extension also opens a new regular window with a temp container tab. How do I suppress this happening?

**Comment by stoically** [comment]
Hi, thanks for the report. I'm unfortunately not able to reproduce this. However, while testing this I've noticed that websites configured with the "Always per Website" preference stopped loading altogether in private windows, maybe the change that fixed that also fixed your issue.

I've released 0.65beta3 - could you install https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/versions/beta and test if it still happens for you? Thanks.

**Comment by Zlewness** [comment]
>  I'd need more informations about your preferences. Are you using Automatic Mode? Advanced configuration "Reopen new Tabs" or "Don't reopen new Tabs"? Does it happen for all links? Do you have a Website pattern configured in "Always per Website"?

Yes Automatic mode, Reopen new tabs, all links that I've tested. Sanitised storage.js renamed as txt attached.

[storage.txt](https://github.com/stoically/temporary-containers/files/1776390/storage.txt)

The beta extension did not fix the issue. If you're on Windows, you can attempt to trigger it by launching firefox (even when open) using `firefox.exe -osint -private-window "<any valid link>"`

**Comment by stoically** [comment]
Just tested on Windows10 by executing `firefox.exe -osint -private-window "https://example.com"`, even with a fresh profile (and version 0.64), and I still unfortunately can't reproduce. Could you maybe try with a fresh profile? Do you have other Add-ons installed+active that could cause this as a side-effect?

**Comment by Zlewness** [comment]
I'm using Firefox Nightly 60a x64 on Windows 7 Pro x64, it happens even on a fresh profile with no addons.

**Comment by stoically** [comment]
No problem. Happens for me with Firefox Nightly with fresh profile and without Add-ons as well (on Linux). :)
